remote_theme: thelehhman/texture
theme: texture
texture:
  title: 杨晓晨
  tagline: iOS Developer. Designer
  date_format: "%b %-d, %Y"
  style: red
  showPicker: false
  # disqus_shortname: games
  showNav: true
  show_excerpts: true
  social_links:
    github:  xiaochenyung
    linkedIn: in/晓晨-杨-374aa41aa # format: locale/username
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"
  