remote_theme: thelehhman/texture
theme: texture
texture:
  title: 杨晓晨
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: red
  showPicker: false
  disqus_shortname: games
  showNav: true
  show_excerpts: true
  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman # format: locale/username
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"
  